<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\core\VisualCompositor.Core.csproj" />
    <ProjectReference Include="..\state\VisualCompositor.State.csproj" />
    <ProjectReference Include="..\rendering\VisualCompositor.Rendering.csproj" />
    <ProjectReference Include="..\osb\VisualCompositor.Osb.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
