<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\core\VisualCompositor.Core.csproj" />
    <ProjectReference Include="..\..\osb\VisualCompositor.Osb.csproj" />
    <ProjectReference Include="..\..\state\VisualCompositor.State.csproj" />
    <ProjectReference Include="..\..\rendering\VisualCompositor.Rendering.csproj" />
    <ProjectReference Include="..\..\ui\VisualCompositor.UI.csproj" />
    <ProjectReference Include="..\..\audio\VisualCompositor.Audio.csproj" />
  </ItemGroup>

</Project>
