using VisualCompositor.Core.Primitives;

namespace VisualCompositor.Core.Snapshots;

/// <summary>Snapshot of a command generated by Expand To Keyframes. Transaction-persistent, redo-after-state.
/// This is the authoritative redo replay payload — redo does NOT recompute, it replays these.</summary>
public sealed class GeneratedCommandSnapshot
{
    /// <summary>The generated command id. Must be non-empty and present in ExpandBlockTransaction.GeneratedCommandIds.</summary>
    public string CommandId { get; init; } = string.Empty;

    /// <summary>Target layer id where the command was generated.</summary>
    public string LayerId { get; init; } = string.Empty;

    /// <summary>Command type letter: M, MX, MY, S, V, R, F, C, P.</summary>
    public string CommandType { get; init; } = string.Empty;

    public OsbEasing Easing { get; init; }

    public double StartTime { get; init; }

    public double EndTime { get; init; }

    public string StartValue { get; init; } = string.Empty;

    public string EndValue { get; init; } = string.Empty;

    /// <summary>Component mask for M/MX/MY/S/V commands.</summary>
    public Vector2ComponentMask ComponentMask { get; init; }

    /// <summary>The source relative command id that generated this command (provenance).</summary>
    public string? SourceRelativeCommandId { get; init; }

    public GeneratedCommandSnapshot DeepClone() => new()
    {
        CommandId = CommandId,
        LayerId = LayerId,
        CommandType = CommandType,
        Easing = Easing,
        StartTime = StartTime,
        EndTime = EndTime,
        StartValue = StartValue,
        EndValue = EndValue,
        ComponentMask = ComponentMask,
        SourceRelativeCommandId = SourceRelativeCommandId,
    };
}
