<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>VisualCompositor.Osb</AssemblyName>
    <RootNamespace>VisualCompositor.Osb</RootNamespace>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Configurations>Debug;Release</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\core\VisualCompositor.Core.csproj" />
  </ItemGroup>

</Project>
