using VisualCompositor.Core.Model.Overrides;
using VisualCompositor.Core.Model.ScriptSync;

namespace VisualCompositor.Core.Model;

/// <summary>The root document model for .storybrewcomp.
/// Per §2: schemaVersion=2. diagnostics NOT stored at top level (regenerated by load/import/validate/export/render).</summary>
public sealed class CompositionDocument
{
    public const int CurrentSchemaVersion = 2;

    public int SchemaVersion { get; set; } = CurrentSchemaVersion;

    /// <summary>Editor/export settings.</summary>
    public Dictionary<string, string> Settings { get; set; } = new();

    /// <summary>OSB [Variables] section: variable name -> value.</summary>
    public Dictionary<string, string> Variables { get; set; } = new();

    /// <summary>Storyboard layers.</summary>
    public List<Layer> Layers { get; set; } = new();

    /// <summary>Timeline markers.</summary>
    public List<Marker> Markers { get; set; } = new();

    /// <summary>Preserved unknown/comment/blank lines.</summary>
    public List<RawBlock> RawBlocks { get; set; } = new();

    /// <summary>All command records keyed by CommandId. Includes Deleted records (persisted by default).</summary>
    public Dictionary<string, CommandRecord> CommandRecords { get; set; } = new();

    /// <summary>History of expanded blocks (audit only, not for undo after reopen).</summary>
    public List<ExpandedBlockHistory> ExpandedBlockHistories { get; set; } = new();

    /// <summary>Script sync manifest (provenance linking sprites/blocks to generating scripts).
    /// Null when script sync is not used.</summary>
    public ScriptSyncManifest? ScriptSyncManifest { get; set; }

    /// <summary>Non-destructive visual overrides and per-difficulty visibility settings.
    /// Null when no overrides exist.</summary>
    public VisualOverrideCollection? VisualOverrides { get; set; }

    /// <summary>Document revision counter (incremented on each successful edit).</summary>
    public long Revision { get; set; }

    /// <summary>Whether the document has unsaved changes.</summary>
    public bool IsDirty { get; set; }

    public CompositionDocument Clone()
    {
        var clone = new CompositionDocument
        {
            SchemaVersion = SchemaVersion,
            Settings = new Dictionary<string, string>(Settings),
            Variables = new Dictionary<string, string>(Variables),
            Layers = Layers.ConvertAll(l => l.Clone()),
            Markers = Markers.ConvertAll(m => m.Clone()),
            RawBlocks = RawBlocks.ConvertAll(r => r.Clone()),
            CommandRecords = CommandRecords.ToDictionary(
                kvp => kvp.Key,
                kvp => kvp.Value.Clone()),
            ExpandedBlockHistories = ExpandedBlockHistories.ConvertAll(h => h.Clone()),
            ScriptSyncManifest = ScriptSyncManifest?.Clone(),
            VisualOverrides = VisualOverrides?.Clone(),
            Revision = Revision,
            IsDirty = IsDirty,
        };
        return clone;
    }
}
