namespace VisualCompositor.Core.Model.ScriptSync;

/// <summary>Collection of script sources and provenance entries, stored in <see cref="CompositionDocument"/>.</summary>
public sealed class ScriptSyncManifest
{
    /// <summary>Known script sources.</summary>
    public List<ScriptSource> Sources { get; set; } = new();

    /// <summary>Provenance entries linking entities to their generating scripts.</summary>
    public List<ScriptProvenance> Provenance { get; set; } = new();

    /// <summary>Gets the script source with the given id, or null.</summary>
    public ScriptSource? GetSource(string scriptId)
        => Sources.FirstOrDefault(s => s.ScriptId == scriptId);

    /// <summary>Gets the provenance entry for the given entity id, or null.</summary>
    public ScriptProvenance? GetProvenanceForEntity(string entityId)
        => Provenance.FirstOrDefault(p => p.EntityId == entityId);

    /// <summary>Gets all provenance entries for entities generated by the given script.</summary>
    public List<ScriptProvenance> GetEntitiesForScript(string scriptId)
        => Provenance.Where(p => p.ScriptId == scriptId).ToList();

    /// <summary>Adds a new source or updates an existing one with the same <see cref="ScriptSource.ScriptId"/>.</summary>
    public void AddOrUpdateSource(ScriptSource source)
    {
        var existing = Sources.FirstOrDefault(s => s.ScriptId == source.ScriptId);
        if (existing != null)
        {
            existing.Identifier = source.Identifier;
            existing.ScriptPath = source.ScriptPath;
            existing.ContentHash = source.ContentHash;
            existing.LastSyncTime = source.LastSyncTime;
            existing.Parameters = new Dictionary<string, string>(source.Parameters);
        }
        else
        {
            Sources.Add(source.Clone());
        }
    }

    /// <summary>Removes the source with the given id and all of its provenance entries.</summary>
    public void RemoveSource(string scriptId)
    {
        Sources.RemoveAll(s => s.ScriptId == scriptId);
        Provenance.RemoveAll(p => p.ScriptId == scriptId);
    }

    /// <summary>Sets the provenance for an entity, replacing any existing entry for that entity.</summary>
    public void SetProvenance(ScriptProvenance provenance)
    {
        var existing = Provenance.FirstOrDefault(p => p.EntityId == provenance.EntityId);
        if (existing != null)
        {
            existing.ScriptId = provenance.ScriptId;
            existing.EntityType = provenance.EntityType;
            existing.SyncState = provenance.SyncState;
        }
        else
        {
            Provenance.Add(provenance.Clone());
        }
    }

    /// <summary>Clears the provenance entry for the given entity id.</summary>
    public void ClearProvenance(string entityId)
        => Provenance.RemoveAll(p => p.EntityId == entityId);

    /// <summary>Whether the manifest is empty (no sources and no provenance).</summary>
    public bool IsEmpty => Sources.Count == 0 && Provenance.Count == 0;

    public ScriptSyncManifest Clone() => new()
    {
        Sources = Sources.ConvertAll(s => s.Clone()),
        Provenance = Provenance.ConvertAll(p => p.Clone()),
    };
}
