namespace VisualCompositor.Core.Validation;

public static class FailureCodes
{
    // ExpandBlockTransaction validation (A, B)
    public const string EXPAND_TRANSACTION_GENERATED_SET_MISMATCH = "EXPAND_TRANSACTION_GENERATED_SET_MISMATCH";
    public const string EXPAND_TRANSACTION_GENERATED_ID_DUPLICATE = "EXPAND_TRANSACTION_GENERATED_ID_DUPLICATE";
    public const string EXPAND_TRANSACTION_GENERATED_SNAPSHOT_ID_EMPTY = "EXPAND_TRANSACTION_GENERATED_SNAPSHOT_ID_EMPTY";
    public const string EXPAND_TRANSACTION_GENERATED_SNAPSHOT_ID_DUPLICATE = "EXPAND_TRANSACTION_GENERATED_SNAPSHOT_ID_DUPLICATE";
    public const string EXPAND_TRANSACTION_GENERATED_SNAPSHOT_NOT_IN_SET = "EXPAND_TRANSACTION_GENERATED_SNAPSHOT_NOT_IN_SET";

    // OriginalBlock record completeness (C)
    public const string EXPAND_ORIGINAL_BLOCK_HEADER_RECORD_MISSING = "EXPAND_ORIGINAL_BLOCK_HEADER_RECORD_MISSING";
    public const string EXPAND_ORIGINAL_BLOCK_RELATIVE_RECORD_MISSING = "EXPAND_ORIGINAL_BLOCK_RELATIVE_RECORD_MISSING";

    // RedoAfter record completeness (D)
    public const string EXPAND_REDO_AFTER_GENERATED_RECORD_MISSING = "EXPAND_REDO_AFTER_GENERATED_RECORD_MISSING";
    public const string EXPAND_REDO_AFTER_SOURCE_SPLIT_RECORD_MISSING = "EXPAND_REDO_AFTER_SOURCE_SPLIT_RECORD_MISSING";

    // DerivedCommandIds partition (E)
    public const string DERIVED_COMMAND_PARTITION_MISMATCH = "DERIVED_COMMAND_PARTITION_MISMATCH";
    public const string DERIVED_COMMAND_OVERLAP = "DERIVED_COMMAND_OVERLAP";
    public const string EXPAND_DERIVED_SOURCE_AMBIGUOUS = "EXPAND_DERIVED_SOURCE_AMBIGUOUS";

    // RawBlock anchor (F, G)
    public const string RAW_BLOCK_ANCHOR_SET_MISMATCH = "RAW_BLOCK_ANCHOR_SET_MISMATCH";
    public const string RAW_ANCHOR_ORPHANED = "RAW_ANCHOR_ORPHANED";
    public const string RAW_BLOCK_ANCHOR_INVALID_COMBINATION = "RAW_BLOCK_ANCHOR_INVALID_COMBINATION";
    public const string RAW_BLOCK_ANCHOR_TARGET_MISSING = "RAW_BLOCK_ANCHOR_TARGET_MISSING";

    // RelativeCommand identity (H)
    public const string RELATIVE_COMMAND_RECORD_MISSING = "RELATIVE_COMMAND_RECORD_MISSING";
    public const string RELATIVE_COMMAND_ID_MISMATCH = "RELATIVE_COMMAND_ID_MISMATCH";

    // HeaderCommand identity (I)
    public const string HEADER_COMMAND_RECORD_MISSING = "HEADER_COMMAND_RECORD_MISSING";
    public const string HEADER_COMMAND_PARENT_MISMATCH = "HEADER_COMMAND_PARENT_MISMATCH";

    // Opaque persistent ids (J)
    public const string ID_EMPTY = "ID_EMPTY";
    public const string ID_DUPLICATE = "ID_DUPLICATE";
    public const string ID_REFERENCE_INVALID = "ID_REFERENCE_INVALID";

    // Redo stack integrity (K)
    public const string REDO_STACK_NOT_CLEARED = "REDO_STACK_NOT_CLEARED";
    public const string STACK_MODIFIED_ON_FAILURE = "STACK_MODIFIED_ON_FAILURE";

    // InsertionAnchor (L)
    public const string INSERTION_ANCHOR_LAYER_MISMATCH = "INSERTION_ANCHOR_LAYER_MISMATCH";
    public const string UNDO_INSERTION_ANCHOR_FALLBACK = "UNDO_INSERTION_ANCHOR_FALLBACK";
    public const string UNDO_LAYER_MISSING = "UNDO_LAYER_MISSING";

    // Serialization validators
    public const string SERIALIZATION_SERIALIZE_FAILED = "SERIALIZATION_SERIALIZE_FAILED";
    public const string SERIALIZATION_DESERIALIZE_FAILED = "SERIALIZATION_DESERIALIZE_FAILED";
    public const string SERIALIZATION_SCHEMA_VERSION_MISMATCH = "SERIALIZATION_SCHEMA_VERSION_MISMATCH";
    public const string SERIALIZATION_LAYER_COUNT_MISMATCH = "SERIALIZATION_LAYER_COUNT_MISMATCH";
    public const string SERIALIZATION_COMMAND_RECORD_COUNT_MISMATCH = "SERIALIZATION_COMMAND_RECORD_COUNT_MISMATCH";
    public const string SERIALIZATION_RAW_BLOCK_COUNT_MISMATCH = "SERIALIZATION_RAW_BLOCK_COUNT_MISMATCH";
    public const string SERIALIZATION_EXPANDED_HISTORY_COUNT_MISMATCH = "SERIALIZATION_EXPANDED_HISTORY_COUNT_MISMATCH";
    public const string SERIALIZATION_SPRITE_COUNT_MISMATCH = "SERIALIZATION_SPRITE_COUNT_MISMATCH";
    public const string SERIALIZATION_BLOCK_COUNT_MISMATCH = "SERIALIZATION_BLOCK_COUNT_MISMATCH";
    public const string SERIALIZATION_PROPERTY_TRACK_COUNT_MISMATCH = "SERIALIZATION_PROPERTY_TRACK_COUNT_MISMATCH";
}
